name: Build CV
on: [push, workflow_dispatch]

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pandoc/actions/setup@v1

      - name: Install LaTeX engine
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               texlive-xetex \
               texlive-latex-base \
               texlive-latex-recommended \
               texlive-latex-extra \
               texlive-fonts-recommended \
               fonts-noto-color-emoji

      - name: Build PDFs
        run: |
          pandoc cv.md --pdf-engine=xelatex -o Edison_Florez_CV.pdf
          pandoc cv.md --pdf-engine=xelatex -M job=data-science -o Edison_Florez_DS.pdf
          pandoc cv.md --pdf-engine=xelatex -M job=academia     -o Edison_Florez_AC.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: Edison_Florez_*.pdf

      # publish PDFs to the gh-pages branch 
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/moving_from_latex_to_md_pandoc'

        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          
          # ---------- checkout (or create) gh-pages
          git fetch origin gh-pages || true
          git switch --force-create gh-pages
          
          # ---------- copy PDFs produced in the build folder
          ls -l
          mkdir -p docs/
          cp Edison_Florez_*.pdf docs/
          
          # ---------- commit & push only if something changed
          git add *.pdf
          if ! git diff --cached --quiet; then
            git commit -m "docs(cv): update generated PDFs [skip ci]"
            git push origin gh-pages
          fi